### ISSUE TITLE
ESP01 board RGB LED CONTROLLER

### ISSUE THREAD

**Issue by vglucas** [HomeKidd/Homekit-WS2812B-controller#13]
I have a WS2812 ESP8266 ESP01 ESP-01 WS2812 RGB as in the photo and use the gpio2, it is possible to have the bin file for this gpio2
![esp01_rgb](https://user-images.githubusercontent.com/49847470/80318466-9dfee680-880a-11ea-86f2-269fd8c6f2cd.jpg)

**Comment by HomeKidd** [comment]
Hi! 
Sorry but this WS2812 board is not compatible with my firmware, first of all not all ESP01 boards are supported, because the _"normal"_ ESP-01 has only 512k flash which is not enough for running HomeKit code + WS2812B effects at the same time, only ESP-01**S** is supported since it has 1MB of flash storage. 

Also GPIO2 cannot be used since the WS2812FX library uses hardware I2S and the pin cannot be changed! More about that in [Wiki page](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki#basic-information)!
