### ISSUE TITLE
Turn on by default

### ISSUE THREAD

**Issue by ducker** [HomeKidd/Homekit-WS2812B-controller#18]
Hi,

thanks for sharing the amazing stuff!!! 

I have only 1 minor issue with the accessory. I'm using one of the led strips in the bower which is not always connected to the electricity and sometimes I switch it on in night. Is is possible to add the additional power state to turn leds on by default when power on the controller? It would be great to have that option.

**Comment by HomeKidd** [comment]
Hi!

Thanks a lot! 😄 
Currently i'm not planning to add this feature because HomeKit via IP needs constant Wi-Fi connection, when you powering up the ESP it takes time to connect to Wi-Fi also, until the ESP not powered on int the Home app it will be unreachable. 

The biggest reason why i'm not planning to add this feature is everyday use: if somehow the esp restarts at night you'll wake up when it will turn of full brightness 😄 I have a [Koogeek](https://www.koogeek.com) HomeKit LED strip and it was a very annoying "feature" to let the default state after powerup to be on.... (until they fixed after 1.5 years..) 😒

For that purpose you dont you use a normal LED strip that turn of when it got power? 😄
