### ISSUE TITLE
Which characteristics are used to implement the effects in the Eve app?

### ISSUE THREAD

**Issue by Zer0x00** [HomeKidd/Homekit-WS2812B-controller#19]
Hello,
not completely related to your project but I'm a homebridge developer and would like to know how you've implemented the effects so that they can be triggered by the Eve app so that I can implement it also in some homebridge related projects.

Since you aren't providing any code (is there a specific reason for this?) but binarys I couldn't look it up.

Anyways thanks for your great projects / work!

Kind Regards

**Comment by HomeKidd** [comment]
Hi!

Its easy, the only thing i've made is an custom characteristic named `Effects` with `uint8` values. Eve app _(and other 3rd party Homekit apps)_ can display any custom Characteristics/Services you've made! 😄

I'm not familiar with homebridge, so i don't know how can you implement custom characteristics. Maybe [this](https://github.com/homebridge/homebridge/issues/1453) can help you how to make it.

The reason why the source code isn't public is because native homekit code is very complex, I'm using a lot of custom libraries and 99% of people cannot compile the code and have issues. Actually with the provided pre-made .bin files for a few people even flashing/setuping the accessory is complicated 😅
