### ISSUE TITLE
NodeMCU connections

### ISSUE THREAD

**Issue by caiotadashi** [HomeKidd/Homekit-WS2812B-controller#22]
Hey, it's me again..
Noob question: I'm planning to use the NodeMCU... I've saw the basic schematic and why I can't connect the RX pin to Din? I've saw many projects with I2S+WS2812B that connects directly.
If I can't connect directly, can I use a logic converter 3.3v-5v to replace the 74AHCT125?

Thank you!

**Comment by HomeKidd** [comment]
Hi!

For a few LEDs You can connect it directly, but i have troubles using it without any logic level converter with larger (50-100+) LED strips. ESP8266 has 3.3V logic level, the LEDs require 5V _( or at least 5V * 0.7 = 3.5V logic high according to the datasheet)_. With e simple logic level converter (BSS138 based) i also have some flickering and color shifting, since i'm using the logic level shifter IC recommended by [Adafruit](https://learn.adafruit.com/adafruit-neopixel-uberguide/the-magic-of-neopixels) all the flickering, color issues are gone 😄 

You can try to connect it directly or using [ other logic level converter](http://s.click.aliexpress.com/e/32VWFbbi) but the [SN74HCT125N](http://s.click.aliexpress.com/e/32VWFbbi) will 100% work! 😄
