### ISSUE TITLE
In my ws2811 green and blue led are schwitched. Could you add a option(maybe in setup to change RGB To RBG)?

### ISSUE THREAD

**Issue by RowMax03** [HomeKidd/Homekit-WS2812B-controller#29]

**Comment by HomeKidd** [comment]
WS2811 strips are not [supported](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki#supported-led-strips) due to this. WS2811 can be only controlled in group of 3 LEDs and basically these are just simply RGB LED strips with WS28xx IC added to it and the R/G/B channels are mixed up. Due to the complexity the code, the effects and these type of “errors” only WS2812 (and upwards) supported only. Also highly recommended to buy from a well known supplier like [BTF-Lighting](http://s.click.aliexpress.com/e/_dUgIncp)

**Comment by RowMax03** [comment]
I bought mine from BTF Lighting and the effects all work fine on mine.I have them currently installed. Am I able to acces the source code? I can change it myself then. I normally use .ino and i have no experience with bin

**Comment by ChopsKingsland** [comment]
That's what I was thinking... because my WS2811 work, and _aren't_ being controlled in groups of 3 (the colour chase works, 1 LED at a time)
