### ISSUE TITLE
Question: How to update without resetting everything

### ISSUE THREAD

**Issue by Caleb79** [HomeKidd/Homekit-WS2812B-controller#32]
Hi,
I've a question how your process of updating the software is? 
Do you always flash the software and all the settings, wifi etc. needs to be done again or is there another way of doing the update?
Thanks.

**Comment by HomeKidd** [comment]
Hi!

Updating the firmware is the same procedure as flashing it first time but **without erasing the flash**. If the flash sector storing the Wifi/HomeKit/setup params are not changed _(mostly i'm using constant flash sectors because of that)_ all the setup should remain the same so no additional re-adding to homekit etc should be done 😄

So if you flash the new firmware without erasing the flash, it will only update the main code, the settings should stay untouched 😄 

I have this info in one of my Wikis but i don't know which one 😂 so i'll add this note 😄
