### ISSUE TITLE
STL for Case Design & Files for Reflow Stencil

### ISSUE THREAD

**Issue by Martin1001** [HomeKidd/Homekit-WS2812B-controller#42]
I really like your PCB designs. 

Unfortunately I can't find the data for the PCB and for the stencil to download at PCB Way. Could you make them available for direct download (possibly in Git)?

In order to design a nice case for the board, a 3D model of the board would be really helpful. Could you also make this available in Git?

**Comment by HomeKidd** [comment]
Hi!

You can order the stencil when you place the order, just check the stencil box😄
![Képernyőfotó 2021-02-27 - 9 48 21](https://user-images.githubusercontent.com/53994826/109382598-b683d580-78e1-11eb-933c-1600b2175542.png)


The STL files are not available because the program I'm using for designing the PCBs cannot export any 3D files, i always design 3D parts using the actual soldered PCB 🤓 but currently i have no time to deal with the enclosure

**Comment by Martin1001** [comment]
@HomeKidd Thank you very much for your awnser.

But I forget the stencil in my previous order and I would like to order it at eisler.net in Germany. This is much faster for me. It would be great if you provide the stencil file.
