### ISSUE TITLE
how to connect my esp8266 12f and ws2812b.

### ISSUE THREAD

**Issue by 172505197** [HomeKidd/Homekit-WS2812B-controller#53]
I've flash the firmware and successfully added accessories to HomeKit. But I have some questions about how to connect my nodemcu (esp8266 12f) and ws2812b.

I'm not sure which io connects to which port on the ws2812b. Should I connect gnd-gnd, vin-5v? and which pin should connect to Di to control the light. Can you tell me how to connect all these things when using this firmware? thank you very much.

**Comment by HomeKidd** [comment]
Hi!
All info you need is available at the [Wiki page](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki/PCB-Design)
😉

**Comment by 172505197** [comment]
I’ve read the wiki and it only says that the output pin is gpio 3, I ve connect the output pin with the di on the light, but it doesn’t work. Are there anything wrong with the other connection ?
![1E0CB7A4-38F4-4651-87C1-DEFDBBABAFEA](https://user-images.githubusercontent.com/68852524/129510555-a5181769-6276-4e53-a548-e66aead5c843.jpeg)
![7C69680A-074A-4689-90F4-C70AAFFF2D1B](https://user-images.githubusercontent.com/68852524/129510575-6ca705f6-3bf9-4c8c-bdc7-f57d04c6d9a8.jpeg)

**Comment by HomeKidd** [comment]
How many LEDs do you want to drive from the ESP itself?
Because it can make around 7-800mA which might be too low amperage for the WS2812 so it doesn't turn on. The ESP itself only can drive around 10 LEDs safely, but it might need a level shifter. 

Also are you sure that the used LED strip is WS28xx? Some others looks the same but not supported.
More info [here](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki#supported-led-strips)

Also the two most important thing:

* WS28xx needs logic level shifter because the ESP has 3.3V pins, the LED strip needs 5V ([more info here](https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices))
* The schematic i've posted powers both the LED strip and ESP from external power supply, not USB  and also has the logic level shifter.  USB is only for flashing the firmware or debug and can cause problems because both USB and the LED strip uses the same pins

**Comment by 172505197** [comment]
I try to make it work like this. As you just said, I think there is not enough power supply. There seems to have a 3v pin and a vin pin on the nodemcu, what should I do to make it have enough power supply.
!
![B467DB80-A6C5-4E26-B72A-2671E3DF310B](https://user-images.githubusercontent.com/68852524/129529998-73907581-4a6e-4dcf-821d-aee0a00e90ae.jpeg)


So if I only  cut a small pieces of the led strip, can it work with the power supply of a usb.
![1DF3BA16-FD54-4805-BA35-417D2CF0D550](https://user-images.githubusercontent.com/68852524/129533919-3ddb5e8e-0748-4475-9ab1-830f88c33129.jpeg)
