### ISSUE TITLE
AP problem

### ISSUE THREAD

**Issue by bizzy985** [HomeKidd/Homekit-WS2812B-controller#60]
hello I flash Sonoff basic without problem but AP not starting. thx

**Comment by HomeKidd** [comment]
Hi! The WS2812B HomeKit code doesnt support Sonoff Basic. Do it on your own risk!

Most likely the AP doesnt show up because of the flash settings, Sonoffs are based on ESP8285 not ESP8266 and it needs other settings for flashing the firmware. See the right setting [here](https://github.com/HomeKidd/ESP8266-HomeKit-Irrigation-System-Eve-Aqua/wiki/Build-Instructions#macos)
